### ISSUE TITLE
ubuntu installation issues

### ISSUE THREAD

**Issue by OferE** [maran/mastercoin-wallet#3]
Hi,
I just successfully installed your  wallet (well done B.T.W!)

You have a typo in the readme - cake instead of cmake

it takes a lot of time (i mean it takes forever :-) )
but finally it worked
so the detailed instructions are as follows:

> sudo apt-get update
> sudo apt-get install ruby ruby-dev gem
> sudo apt-get install libqt4-gui libqt4-dev cmake
> rehash # not sure this one is needed
> sudo gem install mastercoin-wallet
> rehash # this one is needed for sure

to launch it use:
mastercoin-wallet

That worked for me on a fresh Ubuntu 13.04 version

hope this helps.

**Comment by maran** [comment]
Thanks! I will update this for the next push :)

**Comment by seuros** [comment]
@maran  You can edit the readmin inline in Github

**Comment by Exocyst** [comment]
I followed the above updated instructions but I get this error every time on ubuntu 13.04

```
$ mastercoin-wallet 
/var/lib/gems/1.9.1/gems/qtbindings-4.8.5.1/lib/Qt4.rb:27:in `const_missing': uninitialized constant Qt::RubyThreadFix::Queue (NameError)
    from /var/lib/gems/1.9.1/gems/qtbindings-4.8.5.1/lib/Qt4.rb:27:in `<class:RubyThreadFix>'
    from /var/lib/gems/1.9.1/gems/qtbindings-4.8.5.1/lib/Qt4.rb:23:in `<module:Qt>'
    from /var/lib/gems/1.9.1/gems/qtbindings-4.8.5.1/lib/Qt4.rb:22:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/qtbindings-4.8.5.1/lib/Qt.rb:1:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/mastercoin-wallet-0.0.11/lib/mastercoin-wallet.rb:1:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/mastercoin-wallet-0.0.11/bin/mastercoin-wallet:3:in `<top (required)>'
    from /usr/local/bin/mastercoin-wallet:23:in `load'
    from /usr/local/bin/mastercoin-wallet:23:in `<main>'
```

I am totally lost on how to get mastercoin to recognize the gem installed qtbindings

**Comment by OferE** [comment]
did you used:
sudo apt-get install libqt4-gui libqt4-dev cmake

(notice it is cmake)

**Comment by Exocyst** [comment]
I did:

```
sudo apt-get update
sudo apt-get install ruby ruby-dev gem
sudo apt-get install libqt4-gui libqt4-dev cmake
hash -r
sudo gem install mastercoin-wallet
hash -r
mastercoin-wallet
```

Although I don't know if re-hashing was necessary. To be clear: I did the above and got error message. (When I didn't have cmake, I got a different message)

**Comment by OferE** [comment]
not hash -r - rehash - but never mind...

**Comment by Exocyst** [comment]
From https://github.com/ryanmelt/qtbindings/issues/69 I had to edit mastercoin-wallet.rb and call thread first:

```
require 'thread'
require 'Qt'
```

This should be fixed in the next version of qtbindings according to ryanmelt

**Comment by bitcoiners** [comment]
Having issues on my Ubuntu x64 13.10

```
sudo apt-get install libqt4-gui libqt4-dev cmake
```

using rvm with ruby 2.0

```
rvm list

rvm rubies

=* ruby-2.0.0-p353 [ x86_64 ]

gem install mastercoin-wallet
rehash
No command 'rehash' found

mastercoin-wallet
mastercoin-wallet: command not found

```

**Comment by seuros** [comment]
rehash is only valid if you using rbenv

**Comment by bitcoiners** [comment]
even without rehash  mastercoin-wallet command is not found after installing the gem

**Comment by maran** [comment]
Try locate mastercoin-wallet and see if that pops up. It should live somewhere in a directory inside ~/.rvm.

**Comment by bitcoiners** [comment]
Found it 

./.rvm/gems/ruby-2.0.0-p353/gems/mastercoin-wallet-0.0.11/bin/mastercoin-wallet

started it and it poped up a dialog window that wants passwords setup and some private key.. where do I get the private key from?

**Comment by maran** [comment]
These are the keys from your Mastercoin bitcoin address.

**Comment by bitcoiners** [comment]
Can I have more than one Mastercoin address? I added one from my bitcoin-qt wallet and I want to add one for blockchain wallet. How does not get private key from a blockchain wallet address?

**Comment by maran** [comment]
You could in theory switch between two wallet files. They live in ~/.mastercoin-wallet/config.json. 

I never used blockchain so I have no clue how to export a key from there, that's something you can probably look up at their website.
