### ISSUE TITLE
suggestion regarding the first run configuration

### ISSUE THREAD

**Issue by OferE** [maran/mastercoin-wallet#4]
Hi,
I suggest to remove the first run configuration.
Most people (hopefully) will not have a private key of mastercoin, even people that have one will just want to launch your wallet for an initial impression, and maybe want to create an additional address to play with.

For the benefit of those who have a mastercoin address the same page can be used from some kind of menu -> import address.

Hope this helps.

**Comment by maran** [comment]
The application won't work without any data. It's build in such a fashion that it expects all the data the first-run screen gathers. It would mean a lot of rewriting. A few screenshot should suffice for satisfy curiosity for now.
